// <auto-generated />
using System;
using FalkenbergsRevyn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FalkenbergsRevyn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241009074507_added identity")]
    partial class addedidentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FalkenbergsRevyn.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            Category = "Positiva",
                            Content = "Fantastisk show! Helt klart den bästa jag sett.",
                            DatePosted = new DateTime(2024, 9, 10, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6400),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 2,
                            Category = "Positiva",
                            Content = "Musiken var så bra, vilken upplevelse!",
                            DatePosted = new DateTime(2024, 9, 10, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6403),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 3,
                            Category = "Kritik",
                            Content = "Tyvärr tyckte jag inte om skämten i showen.",
                            DatePosted = new DateTime(2024, 9, 11, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6406),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 4,
                            Category = "Kritik",
                            Content = "Belysningen var lite för stark under vissa delar.",
                            DatePosted = new DateTime(2024, 9, 11, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6408),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 5,
                            Category = "Positiva",
                            Content = "Fantastiskt avslut på kvällen, jag skrattade så mycket!",
                            DatePosted = new DateTime(2024, 9, 12, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6410),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 6,
                            Category = "Positiva",
                            Content = "Ser verkligen fram emot nästa års show!",
                            DatePosted = new DateTime(2024, 9, 15, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6412),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 7,
                            Category = "Kritik",
                            Content = "Jag hoppas att ni har bättre skämt nästa gång.",
                            DatePosted = new DateTime(2024, 9, 15, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6414),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 8,
                            Category = "Positiva",
                            Content = "Bra arrangemang, det märks att ni förbereder er i god tid.",
                            DatePosted = new DateTime(2024, 9, 16, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6416),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 9,
                            Category = "Kritik",
                            Content = "Ljudet var inte helt perfekt under vissa repetitioner.",
                            DatePosted = new DateTime(2024, 9, 16, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6418),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 10,
                            Category = "Positiva",
                            Content = "Ska definitivt köpa biljetter så snart de släpps!",
                            DatePosted = new DateTime(2024, 9, 17, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6420),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 11,
                            Category = "Positiva",
                            Content = "Mingelkvällen var så trevlig, bra jobbat!",
                            DatePosted = new DateTime(2024, 9, 20, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6422),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 3
                        },
                        new
                        {
                            CommentId = 12,
                            Category = "Kritik",
                            Content = "Lokalen var lite trång, men annars var det bra.",
                            DatePosted = new DateTime(2024, 9, 20, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6424),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 3
                        },
                        new
                        {
                            CommentId = 13,
                            Category = "Positiva",
                            Content = "Mingelmat och dryck var av högsta kvalitet!",
                            DatePosted = new DateTime(2024, 9, 21, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6426),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 3
                        },
                        new
                        {
                            CommentId = 14,
                            Category = "Kritik",
                            Content = "Skulle vara trevligt med fler sittplatser under minglet.",
                            DatePosted = new DateTime(2024, 9, 21, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6429),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 3
                        },
                        new
                        {
                            CommentId = 15,
                            Category = "Positiva",
                            Content = "Det var fantastiskt att träffa skådespelarna!",
                            DatePosted = new DateTime(2024, 9, 22, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6430),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 3
                        },
                        new
                        {
                            CommentId = 16,
                            Category = "Positiva",
                            Content = "Kostymerna ser otroligt vackra ut!",
                            DatePosted = new DateTime(2024, 9, 22, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6432),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 4
                        },
                        new
                        {
                            CommentId = 17,
                            Category = "Positiva",
                            Content = "Färgerna på kostymerna var fantastiska, snyggt jobbat!",
                            DatePosted = new DateTime(2024, 9, 23, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6434),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 4
                        },
                        new
                        {
                            CommentId = 18,
                            Category = "Kritik",
                            Content = "Några kostymer såg lite ofärdiga ut.",
                            DatePosted = new DateTime(2024, 9, 23, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6436),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 4
                        },
                        new
                        {
                            CommentId = 19,
                            Category = "Positiva",
                            Content = "Ser fram emot att se dem live på scenen!",
                            DatePosted = new DateTime(2024, 9, 24, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6438),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 4
                        },
                        new
                        {
                            CommentId = 20,
                            Category = "Kritik",
                            Content = "Är ni säkra på att alla kostymer är redo för premiären?",
                            DatePosted = new DateTime(2024, 9, 24, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6440),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 4
                        },
                        new
                        {
                            CommentId = 21,
                            Category = "Positiva",
                            Content = "Skådespelarna var lysande! Stort tack!",
                            DatePosted = new DateTime(2024, 9, 25, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6442),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 5
                        },
                        new
                        {
                            CommentId = 22,
                            Category = "Kritik",
                            Content = "Några av scenerna kändes lite utdragna.",
                            DatePosted = new DateTime(2024, 9, 25, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6444),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 5
                        },
                        new
                        {
                            CommentId = 23,
                            Category = "Positiva",
                            Content = "Älskade den nya skådespelaren, grym energi!",
                            DatePosted = new DateTime(2024, 9, 26, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6446),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 5
                        },
                        new
                        {
                            CommentId = 24,
                            Category = "Kritik",
                            Content = "Hoppas att ni förkortar vissa scener till nästa år.",
                            DatePosted = new DateTime(2024, 9, 26, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6447),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 5
                        },
                        new
                        {
                            CommentId = 25,
                            Category = "Positiva",
                            Content = "Perfekt dynamik mellan skådespelarna, fantastisk kemi!",
                            DatePosted = new DateTime(2024, 9, 27, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6449),
                            IsAnswered = false,
                            IsArchived = false,
                            PostId = 5
                        });
                });

            modelBuilder.Entity("FalkenbergsRevyn.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "En beskrivning av den senaste showen.",
                            DateCreated = new DateTime(2024, 9, 9, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6184),
                            Title = "Showen 2024 - Succé!"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Förberedelserna är i full gång inför nästa års show.",
                            DateCreated = new DateTime(2024, 9, 14, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6235),
                            Title = "Förberedelser inför Showen 2025"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "En fantastisk kväll med mingel och underhållning.",
                            DateCreated = new DateTime(2024, 9, 19, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6238),
                            Title = "Mingelkväll på Falkenbergsrevyn"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "En inblick i design och tillverkning av kostymerna.",
                            DateCreated = new DateTime(2024, 9, 21, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6240),
                            Title = "Kostymer för showen 2024"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "Presentation av skådespelarna i årets show.",
                            DateCreated = new DateTime(2024, 9, 24, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6242),
                            Title = "Skådespelarna i årets show"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "En exklusiv titt bakom kulisserna under scenbygget.",
                            DateCreated = new DateTime(2024, 9, 29, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6244),
                            Title = "Bakom kulisserna - Scenbygge"
                        },
                        new
                        {
                            PostId = 7,
                            Content = "Biljetter för nästa års show släpps nu.",
                            DateCreated = new DateTime(2024, 10, 4, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6245),
                            Title = "Biljettsläpp för Showen 2025"
                        },
                        new
                        {
                            PostId = 8,
                            Content = "En presentation av musikerna och låtarna i showen.",
                            DateCreated = new DateTime(2024, 10, 7, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6247),
                            Title = "Musiken i årets revy"
                        },
                        new
                        {
                            PostId = 9,
                            Content = "Hur skådespelarna håller humorn uppe under repetitionerna.",
                            DateCreated = new DateTime(2024, 10, 8, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6249),
                            Title = "Humor bakom kulisserna"
                        },
                        new
                        {
                            PostId = 10,
                            Content = "Recensioner och publikens åsikter om årets revy.",
                            DateCreated = new DateTime(2024, 10, 9, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6251),
                            Title = "Skrattfest på Falkenbergsrevyn"
                        },
                        new
                        {
                            PostId = 11,
                            Content = "En introduktion av en ny skådespelare i revyn.",
                            DateCreated = new DateTime(2024, 10, 2, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6252),
                            Title = "Ny medverkande i showen"
                        },
                        new
                        {
                            PostId = 12,
                            Content = "Information om årets huvudsponsorer.",
                            DateCreated = new DateTime(2024, 9, 27, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6254),
                            Title = "Sponsorer för årets show"
                        },
                        new
                        {
                            PostId = 13,
                            Content = "En guide till vad som serveras under revyn.",
                            DateCreated = new DateTime(2024, 9, 25, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6256),
                            Title = "Mat och dryck på revykvällarna"
                        },
                        new
                        {
                            PostId = 14,
                            Content = "En sammanfattning av publikens favoritmoment.",
                            DateCreated = new DateTime(2024, 10, 6, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6258),
                            Title = "Showens höjdpunkter"
                        },
                        new
                        {
                            PostId = 15,
                            Content = "Beskrivning av det storslagna avslutningsnumret i revyn.",
                            DateCreated = new DateTime(2024, 10, 8, 9, 45, 6, 467, DateTimeKind.Local).AddTicks(6260),
                            Title = "Avslutningsnumret"
                        });
                });

            modelBuilder.Entity("FalkenbergsRevyn.Models.Response", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateResponded")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResponseId");

                    b.HasIndex("CommentId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ResponseId = 1,
                            CommentId = 3,
                            DateResponded = new DateTime(2024, 9, 12, 9, 45, 6, 469, DateTimeKind.Local).AddTicks(3035),
                            ResponseContent = "Tack för din feedback! Vi ser över skämten inför nästa show."
                        },
                        new
                        {
                            ResponseId = 2,
                            CommentId = 4,
                            DateResponded = new DateTime(2024, 9, 12, 9, 45, 6, 469, DateTimeKind.Local).AddTicks(3057),
                            ResponseContent = "Tack för att du påpekade det! Vi kommer att justera belysningen."
                        },
                        new
                        {
                            ResponseId = 3,
                            CommentId = 5,
                            DateResponded = new DateTime(2024, 9, 13, 9, 45, 6, 469, DateTimeKind.Local).AddTicks(3062),
                            ResponseContent = "Vi är glada att du gillade showen! Tack för ditt fina omdöme!"
                        },
                        new
                        {
                            ResponseId = 4,
                            CommentId = 9,
                            DateResponded = new DateTime(2024, 9, 16, 9, 45, 6, 469, DateTimeKind.Local).AddTicks(3064),
                            ResponseContent = "Nästa år satsar vi på ännu bättre ljud!"
                        },
                        new
                        {
                            ResponseId = 5,
                            CommentId = 10,
                            DateResponded = new DateTime(2024, 9, 17, 9, 45, 6, 469, DateTimeKind.Local).AddTicks(3066),
                            ResponseContent = "Vi ser fram emot att se dig nästa år! Biljetterna släpps snart."
                        },
                        new
                        {
                            ResponseId = 6,
                            CommentId = 11,
                            DateResponded = new DateTime(2024, 9, 21, 9, 45, 6, 469, DateTimeKind.Local).AddTicks(3068),
                            ResponseContent = "Kul att du trivdes på mingelkvällen! Tack för din feedback."
                        },
                        new
                        {
                            ResponseId = 7,
                            CommentId = 19,
                            DateResponded = new DateTime(2024, 9, 24, 9, 45, 6, 469, DateTimeKind.Local).AddTicks(3069),
                            ResponseContent = "Vi ser fram emot att du ser kostymerna live på scenen!"
                        },
                        new
                        {
                            ResponseId = 8,
                            CommentId = 22,
                            DateResponded = new DateTime(2024, 9, 27, 9, 45, 6, 469, DateTimeKind.Local).AddTicks(3071),
                            ResponseContent = "Vi håller koll på tidsramarna och ser över de utdragna scenerna."
                        },
                        new
                        {
                            ResponseId = 9,
                            CommentId = 23,
                            DateResponded = new DateTime(2024, 9, 27, 9, 45, 6, 469, DateTimeKind.Local).AddTicks(3073),
                            ResponseContent = "Tack för dina fina ord om våra skådespelare! Vi uppskattar det."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FalkenbergsRevyn.Models.Comment", b =>
                {
                    b.HasOne("FalkenbergsRevyn.Models.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FalkenbergsRevyn.Models.Response", b =>
                {
                    b.HasOne("FalkenbergsRevyn.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FalkenbergsRevyn.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
